// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Registro_Detalles_Suplidores_Blazor.DAL;

namespace Registro_Detalles_Suplidores_Blazor.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20210303181028_Migration_Inicial")]
    partial class Migration_Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("Registro_Detalles_Suplidores_Blazor.Models.Ordenes", b =>
                {
                    b.Property<int>("OrdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<int>("SuplidorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrdenId");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("Registro_Detalles_Suplidores_Blazor.Models.OrdenesDetalles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Costo")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrdenId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId");

                    b.HasIndex("ProductoId");

                    b.ToTable("OrdenesDetalles");
                });

            modelBuilder.Entity("Registro_Detalles_Suplidores_Blazor.Models.Productos", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Costo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Inventario")
                        .HasColumnType("REAL");

                    b.HasKey("ProductoId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            ProductoId = 1,
                            Costo = 25m,
                            Descripcion = "Chocolates",
                            Inventario = 255f
                        },
                        new
                        {
                            ProductoId = 2,
                            Costo = 65m,
                            Descripcion = "Coca Cola",
                            Inventario = 2545f
                        },
                        new
                        {
                            ProductoId = 3,
                            Costo = 95m,
                            Descripcion = "Pepsi",
                            Inventario = 555f
                        },
                        new
                        {
                            ProductoId = 4,
                            Costo = 25m,
                            Descripcion = "Cafe",
                            Inventario = 100f
                        });
                });

            modelBuilder.Entity("Registro_Detalles_Suplidores_Blazor.Models.Suplidores", b =>
                {
                    b.Property<int>("SuplidorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SuplidorId");

                    b.ToTable("Suplidores");

                    b.HasData(
                        new
                        {
                            SuplidorId = 1,
                            Nombres = "Ulises Fermin"
                        },
                        new
                        {
                            SuplidorId = 2,
                            Nombres = "Jesus Lino"
                        },
                        new
                        {
                            SuplidorId = 3,
                            Nombres = "Maximo Martes"
                        });
                });

            modelBuilder.Entity("Registro_Detalles_Suplidores_Blazor.Models.OrdenesDetalles", b =>
                {
                    b.HasOne("Registro_Detalles_Suplidores_Blazor.Models.Ordenes", null)
                        .WithMany("Detalle")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Registro_Detalles_Suplidores_Blazor.Models.Productos", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Registro_Detalles_Suplidores_Blazor.Models.Ordenes", b =>
                {
                    b.Navigation("Detalle");
                });
#pragma warning restore 612, 618
        }
    }
}
